project_name: "sling"

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: ./main.go
    binary: sling
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"